language: android
jdk:
- oraclejdk7
android:
  components:
   - tools
   - platform-tools
   - build-tools-23.0.2
   - android-23
   - extra-android-m2repository
script:
  - ./gradlew build
after_failure:
  - echo "Dumping lint report out to console so it can be reviewed"
  - echo "---app"
  - "cat /home/travis/build/ceduliocezar/sparrow-mvp/app/build/outputs/lint-results.html"
  - echo "---data"
  - "cat /home/travis/build/ceduliocezar/sparrow-mvp/data/build/outputs/lint-results.html"
  - echo "---domain"
  - "cat /home/travis/build/ceduliocezar/sparrow-mvp/domain/build/outputs/lint-results.html"
after_success:
  - coveralls