language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - build-tools-23.0.2
  - android-23
  - extra
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
after_failure: "cat /home/travis/build/ceduliocezar/sparrow-mvp/app/build/outputs/lint-results.html"
